In [1]:
import tensorflow as tf


In [2]:
tf.constant('test')


<tf.Tensor: shape=(), dtype=string, numpy=b'test'>

In [3]:
import torch


In [4]:
torch.manual_seed(42)


In [5]:
print(torch.rand([2,3]))


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [6]:
import numpy as np

In [7]:
xnp= np.array([[1,2,3],[4,5,6]])


In [8]:
xnp

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [10]:
y = torch.tensor([[7,8,9],[10,11,12]])

In [11]:
f = 2*x+y

In [12]:
print(f)

tensor([[ 9, 12, 15],
        [18, 21, 24]])


In [13]:
shape=[2,3]
xzeros = torch.zeros(shape)
xones=torch.ones(shape)
xrnd = torch.rand(shape)
print(xzeros)
print(xones)
print(xrnd)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [15]:
print (torch.rand([2,3]))


tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


In [16]:
f2 = xnp + y

TypeError: unsupported operand type(s) for +: 'numpy.ndarray' and 'Tensor'

In [17]:
f2 = y+xnp


In [18]:
print(f2)
f2.type()

tensor([[ 8, 10, 12],
        [14, 16, 18]])


'torch.LongTensor'

In [19]:
xtensor = torch.from_numpy(xnp)

In [20]:
print(xtensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [21]:
print(xtensor.type())

torch.LongTensor


In [22]:
print(f.type())

torch.LongTensor


In [23]:
fnp = f.numpy()

In [24]:
print(type(fnp))

<class 'numpy.ndarray'>


In [25]:
a = np.ones(3)

In [26]:
a

array([1., 1., 1.])

In [27]:
t = torch.from_numpy(a)

In [28]:
b = t.numpy()

In [29]:
b[1] = 0

In [30]:
print(a[1] == b[1])

True


In [31]:
print(t)

tensor([1., 0., 1.], dtype=torch.float64)
