In [1]:
import tensorflow as tf


In [2]:
tf.constant('test')


<tf.Tensor: shape=(), dtype=string, numpy=b'test'>

In [3]:
import torch


In [4]:
torch.manual_seed(42)


In [5]:
print(torch.rand([2,3]))


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [6]:
import numpy as np

In [7]:
xnp= np.array([[1,2,3],[4,5,6]])


In [8]:
xnp

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
y = torch.tensor()